$(document).ready(
    function(){
       $(".radius1").click(
            function(){
               $(".main-div").css("border-radius","10px")
            }
        )
        $(".radius2").click(
            function(){
               $(".main-div").css("border-radius","30px")
            }
        )
        $(".radius3").click(
            function(){
               $(".main-div").css("border-radius","50px")
            }
        )
        $(".bg1").click(
            function(){
               $(".main-div").css("background-color","red")
            }
        )
        $(".bg2").click(
            function(){
               $(".main-div").css("background-color","yellow")
            }
        )
        $(".bg3").click(
            function(){
               $(".main-div").css("background-color","blue")
            }
        )
        $(".ta1").click(
            function(){
               $(".main-div").css("text-align","left")
            }
        )
        $(".ta2").click(
            function(){
               $(".main-div").css("text-align","center")
            }
        )
        $(".ta3").click(
            function(){
               $(".main-div").css("text-align","right")
            }
        )
        $(".p1").click(
            function(){
               $(".main-div").css("margin-left","0px")
            }
        )
        $(".p2").click(
            function(){
               $(".main-div").css("margin-left","40%")
            }
        )
        $(".p3").click(
            function(){
               $(".main-div").css("margin-left","70%")
            }
        )

    }
)